apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: rabbitmq
spec:
  replicas: 1
  service:
    type: ClusterIP
  persistence:
    storageClassName: "gp2"
    storage: 2Gi