apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: rabbitmq
spec:
  replicas: 1
  service:
    type: ClusterIP
  persistence:
    storageClassName: "csi-cinder-classic"
    storage: 20Gi
  resources:
    limits:
      memory: 8Gi
    requests:
      cpu: "2"
      memory: 4Gi